import { ApiError } from '@/components/api-error'
import { DataRow, Section } from '@/components/section'
import { api } from '@/lib/api'
import { formatNumber } from '@/lib/format'
import type { LabRequest } from '@/lib/types'

export const dynamic = 'force-dynamic'

const PRESET: LabRequest = {
  curveMode: 'EVENT_ADAPTIVE',
  segments: 8,
  referencePrice: '150',
  referenceConfidenceBps: '40',
  currentPremiumBps: '200',
  eventIntensity: '0.7',
  targetLiquidity: '250000',
  migrationQuoteThreshold: '100000',
  quoteMint: 'So11111111111111111111111111111111111111112',
  scenario: 'IPO_IMMINENT',
}

export default async function WhyMeteoraPage() {
  const result = await api.dbcLab(PRESET)

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="label">Why Meteora</p>
        <h1 className="mt-1 text-2xl font-semibold">Transition state, made programmable</h1>
        <p className="mt-2 max-w-3xl text-sm" style={{ color: 'var(--muted)' }}>
          Auctra does not merely monitor markets. It converts transition state into configurable liquidity
          mechanics, and Meteora DBC is the primitive that makes those mechanics programmable. The parameters
          below are generated by the same engine the plans use.
        </p>
      </div>

      {!result.ok ? (
        <ApiError error={result.error} message={result.message} />
      ) : (
        <>
          <Section id="params" title="Actual generated parameters">
            <div className="grid gap-x-8 lg:grid-cols-2">
              <div>
                <DataRow label="BUILD CURVE MODE" value={result.data.dbcPlan.curveMode} />
                <DataRow label="CURVE SEGMENTS" value={String(result.data.dbcPlan.segments)} />
                <DataRow label="BASE FEE MODE" value={result.data.feePolicy.mode === 'exponential' ? 'FEE SCHEDULER EXPONENTIAL' : 'FEE SCHEDULER LINEAR'} />
                <DataRow label="FEE SCHEDULE" value={`${result.data.feePolicy.startingFeeBps} → ${result.data.feePolicy.endingFeeBps} bps over ${result.data.feePolicy.durationSeconds}s`} />
                <DataRow label="ACTIVATION TYPE" value={result.data.dbcPlan.activationType} />
              </div>
              <div>
                <DataRow label="ACTIVATION POINT" value={result.data.dbcPlan.activation.timestamp ?? 'n/a'} />
                <DataRow label="QUOTE MINT" value={result.data.dbcPlan.quoteMint} />
                <DataRow label="MIGRATION OPTION" value={result.data.dbcPlan.migrationOption} />
                <DataRow label="MIGRATION THRESHOLD" value={result.data.dbcPlan.migrationQuoteThreshold} />
                <DataRow label="CONCENTRATION (HHI)" value={formatNumber(result.data.liquidityPlan.concentration.value, 4)} />
              </div>
            </div>
          </Section>

          <Section id="migration" title="Protocol condition vs Auctra recommendation">
            <p className="text-sm" style={{ color: 'var(--muted)' }}>
              The migration threshold is a protocol configuration. Meteora migrates a DBC pool once the pool
              quote balance reaches it, and that migration is permissionless. Auctra shows its own
              recommendation separately and never claims it can block migration.
            </p>
            <p className="mt-3 text-xs" style={{ color: 'var(--faint)' }}>
              {result.data.simulation.comparison.note}
            </p>
          </Section>
        </>
      )}
    </div>
  )
}
