'use client'

import { useState, type FormEvent } from 'react'
import { ComparisonTable } from '@/components/comparison-table'
import { CurveChart } from '@/components/curve-chart'
import { DataRow, Section } from '@/components/section'
import { api } from '@/lib/api'
import { formatNumber } from '@/lib/format'
import type { LabRequest, LabResponse } from '@/lib/types'

const MODES = ['REFERENCE_CENTERED', 'TRANSITION_WIDE', 'EVENT_ADAPTIVE'] as const
const SCENARIOS = [
  'NORMAL',
  'IPO_ANNOUNCED',
  'IPO_IMMINENT',
  'PUBLIC_MARKET_OPENS',
  'PUBLIC_MARKET_PRICE_GAP',
  'HIGH_REFERENCE_UNCERTAINTY',
  'CONVERSION_DEADLINE_APPROACHING',
  'ACQUISITION_EVENT',
  'NO_TARGET_ASSET',
]
const DEFAULT_QUOTE_MINT = 'So11111111111111111111111111111111111111112'
const inputClass = 'panel-2 w-full px-3 py-2 text-sm'

/**
 * DBC curve lab (AUCTRA.md Section 54).
 * Every output is generated by the same deterministic policy engine the plans use.
 */
export default function DbcLabPage() {
  const [form, setForm] = useState({
    curveMode: 'EVENT_ADAPTIVE' as (typeof MODES)[number],
    segments: '8',
    referencePrice: '150',
    referenceConfidenceBps: '40',
    currentPremiumBps: '200',
    eventIntensity: '0.7',
    targetLiquidity: '250000',
    migrationQuoteThreshold: '100000',
    quoteMint: DEFAULT_QUOTE_MINT,
    scenario: 'IPO_IMMINENT',
  })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<LabResponse | null>(null)

  function set<K extends keyof typeof form>(key: K, value: (typeof form)[K]) {
    setForm((current) => ({ ...current, [key]: value }))
  }

  async function submit(event: FormEvent) {
    event.preventDefault()
    setBusy(true)
    setError(null)
    const body: LabRequest = {
      curveMode: form.curveMode,
      segments: Number(form.segments),
      referencePrice: form.referencePrice,
      referenceConfidenceBps: form.referenceConfidenceBps,
      currentPremiumBps: form.currentPremiumBps,
      eventIntensity: form.eventIntensity,
      targetLiquidity: form.targetLiquidity,
      migrationQuoteThreshold: form.migrationQuoteThreshold,
      quoteMint: form.quoteMint,
      scenario: form.scenario,
    }
    const response = await api.dbcLab(body)
    if (response.ok) setResult(response.data)
    else setError(response.message ?? response.error)
    setBusy(false)
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="label">DBC curve lab</p>
        <h1 className="mt-1 text-2xl font-semibold">How parameters change transition behaviour</h1>
        <p className="mt-2 max-w-3xl text-sm" style={{ color: 'var(--muted)' }}>
          Adjust the policy inputs and inspect the resulting Transition Curve, fee schedule and DBC
          configuration. Outputs come from the deterministic engine; nothing here is deployed.
        </p>
      </div>

      <form onSubmit={submit} className="panel grid gap-4 p-5 md:grid-cols-3">
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-mode" className="label">
            Curve mode
          </label>
          <select
            id="lab-mode"
            value={form.curveMode}
            onChange={(event) => set('curveMode', event.target.value as (typeof MODES)[number])}
            className={inputClass}
            style={{ color: 'var(--ink)' }}
          >
            {MODES.map((mode) => (
              <option key={mode} value={mode}>
                {mode.replaceAll('_', ' ')}
              </option>
            ))}
          </select>
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-segments" className="label">
            Segments
          </label>
          <input id="lab-segments" type="number" min={2} max={16} value={form.segments} onChange={(e) => set('segments', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-reference" className="label">
            Reference price
          </label>
          <input id="lab-reference" value={form.referencePrice} onChange={(e) => set('referencePrice', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-conf" className="label">
            Reference confidence (bps)
          </label>
          <input id="lab-conf" value={form.referenceConfidenceBps} onChange={(e) => set('referenceConfidenceBps', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-premium" className="label">
            Current premium (bps)
          </label>
          <input id="lab-premium" value={form.currentPremiumBps} onChange={(e) => set('currentPremiumBps', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-intensity" className="label">
            Event intensity (0–1)
          </label>
          <input id="lab-intensity" value={form.eventIntensity} onChange={(e) => set('eventIntensity', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-liquidity" className="label">
            Liquidity target
          </label>
          <input id="lab-liquidity" value={form.targetLiquidity} onChange={(e) => set('targetLiquidity', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-threshold" className="label">
            Migration threshold
          </label>
          <input id="lab-threshold" value={form.migrationQuoteThreshold} onChange={(e) => set('migrationQuoteThreshold', e.target.value)} className={inputClass} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lab-scenario" className="label">
            Simulation scenario
          </label>
          <select
            id="lab-scenario"
            value={form.scenario}
            onChange={(e) => set('scenario', e.target.value)}
            className={inputClass}
            style={{ color: 'var(--ink)' }}
          >
            {SCENARIOS.map((scenario) => (
              <option key={scenario} value={scenario}>
                {scenario.replaceAll('_', ' ')}
              </option>
            ))}
          </select>
        </div>
        <div className="md:col-span-3">
          <button
            type="submit"
            disabled={busy}
            className="px-5 py-2 text-sm font-medium"
            style={{ background: 'var(--accent-dim)', border: '1px solid var(--accent)', color: 'var(--ink)' }}
          >
            {busy ? 'Computing…' : 'Generate configuration'}
          </button>
        </div>
      </form>

      {error ? (
        <p className="panel p-4 text-sm" role="alert" style={{ color: 'var(--danger)' }}>
          {error}
        </p>
      ) : null}

      {result ? (
        <>
          <Section id="curve" title="Transition curve">
            <CurveChart points={result.curve.points} referencePrice={result.curve.referencePrice} title="Liquidity weight" />
          </Section>
          <Section id="liquidity-graph" title="Liquidity allocation">
            <CurveChart points={result.curve.points} referencePrice={result.curve.referencePrice} title="Liquidity per segment" metric="liquidity" />
          </Section>

          <div className="grid gap-5 lg:grid-cols-2">
            <Section id="fees" title="Fee schedule">
              <DataRow label="Mode" value={result.feePolicy.mode} />
              <DataRow label="Starting fee" value={`${result.feePolicy.startingFeeBps} bps`} />
              <DataRow label="Ending fee" value={`${result.feePolicy.endingFeeBps} bps`} />
              <DataRow label="Duration" value={`${result.feePolicy.durationSeconds}s`} />
              <DataRow label="Activation" value={`${result.activation.type}${result.activation.timestamp ? ` · ${result.activation.timestamp}` : ''}`} mono={false} />
              <DataRow label="Reason" value={result.feePolicy.reason} mono={false} />
            </Section>
            <Section id="policy" title="Policy inputs and outputs">
              <DataRow label="Curve mode" value={result.dbcPlan.curveMode} />
              <DataRow label="Segments" value={String(result.dbcPlan.segments)} />
              <DataRow label="Concentration (HHI)" value={formatNumber(result.liquidityPlan.concentration.value, 4)} />
              <DataRow label="Initial curve width" value={formatNumber(result.liquidityPlan.initialCurveWidth.value, 4)} />
              <DataRow label="Migration threshold" value={result.dbcPlan.migrationQuoteThreshold} />
              <DataRow label="Quote mint" value={result.dbcPlan.quoteMint} />
            </Section>
          </div>

          <Section id="simulation" title="Simulation">
            <ComparisonTable comparison={result.simulation.comparison} />
          </Section>

          <Section
            id="validation"
            title="Config validation"
            aside={
              result.validation && result.validation.length > 0 ? (
                <span className="tone-warn">{result.validation.length} issue(s)</span>
              ) : (
                <span className="tone-ok">valid</span>
              )
            }
          >
            {result.validation && result.validation.length > 0 ? (
              <ul className="flex flex-col gap-1 text-xs" style={{ color: 'var(--warn)' }}>
                {result.validation.map((issue) => (
                  <li key={issue.code}>
                    {issue.code}: {issue.message}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm" style={{ color: 'var(--muted)' }}>
                The generated configuration passes the recorded protocol constraints.
              </p>
            )}
            <details className="panel-2 mt-4 p-3">
              <summary className="cursor-pointer text-xs" style={{ color: 'var(--muted)' }}>
                Raw configuration (JSON)
              </summary>
              <pre className="mono mt-3 max-h-96 overflow-auto text-xs">{JSON.stringify(result.dbcPlan, null, 2)}</pre>
            </details>
          </Section>
        </>
      ) : null}
    </div>
  )
}
